Overall purpose of the numpy.random package:

The overall purpose of the numpy.random package is to generate random numbers.
Possible reasons for generating random numbers are to simulate data that is inaccessible, or to create data in order to practice data representation.

Below I will explore several functions of the numpy.random package to demonstrate what they do and how they work.

The first sampling of numpy functions to demonstrate is a set of functions called simple random data.
These are integers, random, choice, and bytes.

Integers:

In [1]:
import numpy as np
rng = np.random.default_rng()
rng.integers(4, size=10)

#A random array of 10 integers up to, but not including, 4 was generated in the output.


array([2, 2, 0, 3, 0, 3, 3, 0, 2, 2])

In [ ]:
Random:

In [1]:
import numpy as np
rng = np.random.default_rng()
rng.random()

#Generates a random number as a float.

0.6564531657861813

In [3]:
type(rng.random())
rng.random((5,))

#Generates an array of 5 floats. 
#If you choose a different number, like 3 for example, you would get an array of three floats.

array([0.49980091, 0.93818459, 0.62088411, 0.04061112, 0.53066427])

In [5]:
#You can also create a three by two array with the following:
#This method gives you an array of two columns of random floats up to, but not including, 4.

4 * rng.random((3, 2)) - 4

array([[-3.90487368, -2.57438514],
       [-1.61396644, -1.09116634],
       [-2.36571758, -0.27617533]])

Choice:

In [2]:
#This function allows us to specify probability for each value.

import numpy as np
rng = np.random.default_rng()
rng.choice(7, 4)

#Outputs an array of 4 integers up to but never including 7

array([4, 2, 4, 1])

In [31]:
import numpy as np
rng = np.random.default_rng()
rng.choice(7, 4)
rng.choice(([4, 2, 4, 1]), p=([0.1, 0.3, 0.6, 0.0]), size=(100))

#Output is a 1-D Array containing 100 values where each value has to be 4,2, or 1.
#4 is assigned to 0.1, 2 to 0.3, 4 again to 0.6, and 1 to 0.0
#p always needs to be equal to 1


array([4, 4, 4, 4, 2, 4, 4, 4, 2, 2, 2, 4, 4, 2, 2, 4, 4, 4, 4, 2, 2, 4,
       2, 2, 2, 4, 2, 2, 4, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2,
       4, 4, 4, 4, 4, 2, 4, 4, 2, 2, 4, 2, 4, 2, 4, 4, 4, 4, 2, 4, 4, 2,
       4, 4, 4, 4, 2, 4, 4, 4, 2, 4, 4, 4, 4, 4, 4, 4, 4, 2, 4, 2, 4, 4,
       4, 4, 4, 2, 2, 4, 4, 4, 4, 2, 4, 2])

In [38]:
#You don't have to use only numbers for the arrays, but can also use lists.

import numpy as np
composers_arr = ['Mozart' , 'Bach' , 'Handel' , 'Beethoven' , 'Haydn' , 'Vivaldi']
rng.choice(composers_arr, 5 , p=([0.2, 0.1, 0.1, 0.1, 0.2, 0.3]))


array(['Beethoven', 'Handel', 'Bach', 'Bach', 'Mozart'], dtype='<U9')

Bytes:

In [1]:
#This function returns random bytes

import numpy as np
np.random.default_rng().bytes(20)

b'\xe6\x97\xe2\xb0h\xc5\xe4a\xf80\xa1\x1b!M\xed\x8e\x85\x0e%\xa3'

The second sampling of Numpy functions to demonstrate are the two permutations functions: shuffle and permutation.

Shuffle:

In [3]:
#The shuffle method allows us to change or shuffle the elements in an array, but the contents stay the same.

import numpy as np
rng = np.random.default_rng()
arr = np.arange(12)
#rng.shuffle(arr)
arr

#Here, there is a random array of integers up to but not including 12

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
import numpy as np
rng = np.random.default_rng()
arr = np.arange(12)
rng.shuffle(arr) #By adding the Shuffle method, we've changed the order of the integers in the array.
arr

array([ 6,  0,  8,  2,  7,  1,  3, 10,  9, 11,  4,  5])

A practical/real world usage for the shuffle method would be for the lottery.
You draw a set number of lotto balls with numbers on them, 6 numbers for example, out of 100.
You could use the shuffle method to choose the 6 random numbers:

In [2]:
import numpy as np
lotto = list(range(1, 100)) #create a list of 100 numbers
x = np.array(lotto) #convert to a numpy array
np.random.shuffle(x) #shuffle the numbers
x
draw = x[0:6] #output first 6 random numbers
'The lotto numbers are', draw # dispay the lotto numbers

('The lotto numbers are', array([35, 87, 68, 48, 50, 99]))

Permutations:

In [2]:
#The permutations method makes a copy of the original array and then returns a rearrangement of it.

import numpy as np
rng = np.random.default_rng()
arr = np.arange(15)
arr #random array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
import numpy as np
rng = np.random.default_rng()
arr = np.arange(15)
rng.permutation(15) #rerranged array

array([ 0, 11, 13,  9,  1,  5,  7,  3,  4,  2,  8, 14, 12,  6, 10])

A practical usage for the permutations method would be when generating a good password for a computer or website.

In [7]:
import numpy as np
letnumb = np.array(['1', 'n', 'z', 'h', 't', '8', 'J', 'K', '6', '4', '9', 'G'])
password = np.random.permutation(letnumb)
print('Password is=', password[1:9])

Password is= ['t' 'G' '8' '1' 'z' 'J' '4' '6']


References for Programming for Data Analytics Practical Task:

https://www.pcg-random.org/index.html

https://towardsdatascience.com/how-to-generate-pseudo-random-datasets-in-python-start-from-scratch-with-numpy-faker-c5661e3bc58b

https://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/Working%20With%20Markdown%20Cells.html

https://www.practicaldatascience.org/html/exercises/Exercise_numpy.html

https://numpy.org/doc/stable/user/absolute_beginners.html#basic-array-operations

https://numpy.org/doc/stable/reference/random/generator.html

https://www.w3schools.com/python/numpy_random.asp

https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.integers.html#numpy.random.Generator.integers

https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.logistic.html#numpy.random.Generator.logistic

https://github.com/oreillyh/Programming-for-DA---Assignments/blob/master/Programming%20for%20Data%20Analytics%20Assignment%201.ipynb

https://en.wikipedia.org/wiki/Normal_distribution

https://en.wikipedia.org/wiki/Exponential_distribution

https://en.wikipedia.org/wiki/Logistic_distribution

https://en.wikipedia.org/wiki/Poisson_distribution

https://en.wikipedia.org/wiki/Binomial_distribution 

https://www.youtube.com/watch?v=kyjlxsLW1Is&ab_channel=zedstatistics