Overall purpose of the numpy.random package:

The overall purpose of the numpy.random package is to generate random numbers.
Possible reasons for generating random numbers are to simulate data that is inaccessible, or to create data in order to practice data representation.

Below I will explore several functions of the numpy.random package to demonstrate what they do and how they work.

The first sampling of numpy functions to demonstrate is a set of functions called simple random data.
These are integers, random, choice, and bytes.

Integers:

In [1]:
import numpy as np
rng = np.random.default_rng()
rng.integers(4, size=10)

#A random array of 10 integers up to, but not including, 4 was generated in the output.


array([2, 2, 0, 3, 0, 3, 3, 0, 2, 2])

In [ ]:
Random:

In [1]:
import numpy as np
rng = np.random.default_rng()
rng.random()

#Generates a random number as a float.

0.6564531657861813

In [3]:
type(rng.random())
rng.random((5,))

#Generates an array of 5 floats. 
#If you choose a different number, like 3 for example, you would get an array of three floats.

array([0.49980091, 0.93818459, 0.62088411, 0.04061112, 0.53066427])

In [5]:
#You can also create a three by two array with the following:
#This method gives you an array of two columns of random floats up to, but not including, 4.

4 * rng.random((3, 2)) - 4

array([[-3.90487368, -2.57438514],
       [-1.61396644, -1.09116634],
       [-2.36571758, -0.27617533]])

Choice:

In [2]:
#This function allows us to specify probability for each value.

import numpy as np
rng = np.random.default_rng()
rng.choice(7, 4)

#Outputs an array of 4 integers up to but never including 7

array([4, 2, 4, 1])

In [31]:
import numpy as np
rng = np.random.default_rng()
rng.choice(7, 4)
rng.choice(([4, 2, 4, 1]), p=([0.1, 0.3, 0.6, 0.0]), size=(100))

#Output is a 1-D Array containing 100 values where each value has to be 4,2, or 1.
#4 is assigned to 0.1, 2 to 0.3, 4 again to 0.6, and 1 to 0.0
#p always needs to be equal to 1


array([4, 4, 4, 4, 2, 4, 4, 4, 2, 2, 2, 4, 4, 2, 2, 4, 4, 4, 4, 2, 2, 4,
       2, 2, 2, 4, 2, 2, 4, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2,
       4, 4, 4, 4, 4, 2, 4, 4, 2, 2, 4, 2, 4, 2, 4, 4, 4, 4, 2, 4, 4, 2,
       4, 4, 4, 4, 2, 4, 4, 4, 2, 4, 4, 4, 4, 4, 4, 4, 4, 2, 4, 2, 4, 4,
       4, 4, 4, 2, 2, 4, 4, 4, 4, 2, 4, 2])

In [38]:
#You don't have to use only numbers for the arrays, but can also use lists.

import numpy as np
composers_arr = ['Mozart' , 'Bach' , 'Handel' , 'Beethoven' , 'Haydn' , 'Vivaldi']
rng.choice(composers_arr, 5 , p=([0.2, 0.1, 0.1, 0.1, 0.2, 0.3]))


array(['Beethoven', 'Handel', 'Bach', 'Bach', 'Mozart'], dtype='<U9')

Bytes: